<a href="https://colab.research.google.com/github/InGev007/startup_acd/blob/main/lesson37/lesson37_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
import numpy as np

dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/communities.csv')

numeric_cols = dataset.select_dtypes(include=np.number).columns.tolist()
dataset = dataset[numeric_cols]
dataset.head()

,8,1,0.19,0.33,0.02,0.9,0.12,0.17,0.34,0.47,...,0.12.1,0.42,0.5.1,0.51.1,0.64,0.12.2,0.26.1,0.2.1,0.32.2,0.2.2
0,53,1,0.00,0.16,0.12,0.74,0.45,0.07,0.26,0.59,...,0.21,0.50,0.34,0.60,0.52,0.02,0.12,0.45,0.0,0.67
1,24,1,0.00,0.42,0.49,0.56,0.17,0.04,0.39,0.47,...,0.14,0.49,0.54,0.67,0.56,0.01,0.21,0.02,0.0,0.43
2,34,1,0.04,0.77,1.00,0.08,0.12,0.10,0.51,0.50,...,0.19,0.30,0.73,0.64,0.65,0.02,0.39,0.28,0.0,0.12
3,42,1,0.01,0.55,0.02,0.95,0.09,0.05,0.38,0.38,...,0.11,0.72,0.64,0.61,0.53,0.04,0.09,0.02,0.0,0.03
4,6,1,0.02,0.28,0.06,0.54,1.00,0.25,0.31,0.48,...,0.70,0.42,0.49,0.73,0.64,0.01,0.58,0.10,0.0,0.14

In [17]:
from sklearn.linear_model import Lasso, Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# Розділити дані на тренувальні та тестові
X = dataset.drop('1', axis=1)
y = dataset['1']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# L1 (Lasso) регуляризація
lasso = Lasso(alpha=0.1)
lasso.fit(X_train, y_train)
y_pred = lasso.predict(X_test)
print('Lasso MSE:', mean_squared_error(y_test, y_pred))

# L2 (Ridge) регуляризація
ridge = Ridge(alpha=0.1)
ridge.fit(X_train, y_train)
y_pred = ridge.predict(X_test)
print('Ridge MSE:', mean_squared_error(y_test, y_pred))

Lasso MSE: 8.210514297547833
Ridge MSE: 8.672724361717327

Після застосування регуляризації, можна порівняти результати за допомогою середньоквадратичної помилки (MSE). Оцінка MSE дає змогу зрозуміти, наскільки добре модель прогнозує цільову змінну. Чим менше значення MSE, тим краще прогнозує модель.

У випадку даного датасету, результати показують, що L1 (Lasso) регуляризація дає кращі результати, ніж L2 (Ridge)  регуляризація. Результати можуть відрізнятися