1. Створіть xls-документ, що містить дані про марки автомобілів, їхню вартість, споживання палива, максимальну швидкість та вантажопідйомність. Кількість записів у документі – 20.

In [6]:
import pandas as pd

# Створення таблиці з даними
data = {
    'Марка автомобіля': ['Toyota', 'Honda', 'BMW', 'Mercedes', 'Ford', 'Nissan', 'Audi', 'Chevrolet', 'Kia', 'Hyundai', 'Lexus', 'Mazda', 'Peugeot', 'Renault', 'Subaru', 'Suzuki', 'Volkswagen', 'Volvo', 'Opel', 'Fiat'],
    'Вартість, тис. дол.': [30, 25, 50, 60, 20, 27, 55, 18, 22, 23, 40, 28, 32, 24, 35, 19, 33, 45, 21, 26],
    'Споживання палива, л/100 км': [6.5, 7.0, 8.5, 9.0, 7.5, 8.0, 8.2, 7.2, 6.8, 7.5, 7.0, 6.8, 6.9, 7.5, 8.0, 6.5, 7.0, 8.5, 7.2, 6.0],
    'Максимальна швидкість, км/год': [200, 190, 240, 250, 180, 200, 220, 170, 180, 190, 220, 200, 190, 180, 210, 190, 200, 230, 170, 160],
    'Вантажопідйомність, т': [1.5, 1.3, 1.8, 1.9, 1.2, 1.4, 1.7, 1.1, 1.2, 1.3, 1.8, 1.4, 1.3, 1.5, 1.6, 1.3, 1.4, 1.7, 1.2, 1.1]
}

df = pd.DataFrame(data)

# експорт DataFrame до Excel
df.to_excel('автомобілі.xls', index=False)
df

C:\Users\ingev\AppData\Local\Temp\ipykernel_5736\2217030582.py:15: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  df.to_excel('автомобілі.xls', index=False)

,Марка автомобіля,"Вартість, тис. дол.","Споживання палива, л/100 км","Максимальна швидкість, км/год","Вантажопідйомність, т"
0,Toyota,30,6.5,200,1.5
1,Honda,25,7.0,190,1.3
2,BMW,50,8.5,240,1.8
3,Mercedes,60,9.0,250,1.9
4,Ford,20,7.5,180,1.2
5,Nissan,27,8.0,200,1.4
6,Audi,55,8.2,220,1.7
7,Chevrolet,18,7.2,170,1.1
8,Kia,22,6.8,180,1.2
9,Hyundai,23,7.5,190,1.3
10,Lexus,40,7.0,220,1.8
11,Mazda,28,6.8,200,1.4
12,Peugeot,32,6.9,190,1.3
13,Renault,24,7.5,180,1.5
14,Subaru,35,8.0,210,1.6
15,Suzuki,19,6.5,190,1.3
16,Volkswagen,33,7.0,200,1.4
17,Volvo,45,8.5,230,1.7
18,Opel,21,7.2,170,1.2
19,Fiat,26,6.0,160,1.1